name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Обновляем код
          cd /var/www/vaults-cc
          git pull origin main
          
          # Устанавливаем зависимости и билдим
          npm ci
          npm run build
          
          # Устанавливаем/настраиваем Nginx если нужно
          if ! command -v nginx &> /dev/null; then
            apt update
            apt install -y nginx certbot python3-certbot-nginx
            
            # Копируем конфигурацию Nginx
            cp nginx.conf /etc/nginx/sites-available/vaults-cc
            ln -sf /etc/nginx/sites-available/vaults-cc /etc/nginx/sites-enabled/
            rm -f /etc/nginx/sites-enabled/default
            
            # Проверяем и запускаем Nginx
            nginx -t && systemctl restart nginx
            systemctl enable nginx
            
            # Получаем SSL сертификат
            certbot --nginx -d vaults.cc --non-interactive --agree-tos --email admin@vaults.cc
          fi
          
          # Перезапускаем PM2
          pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
          pm2 save 